[package]
name = "cxx-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.107"
cxx-qt = "0.5.3"
cxx-qt-lib = "0.5.3"
md5 = "0.7.0"

[build-dependencies]
cxx-qt-build = "0.5.3"
